package thursdaylab;

import java.nio.channels.AlreadyBoundException;

public class Exception
{
      public static void main(String arg[])
      {
     System.out.println("main method started");
   
     try
     {
   
     try
     {
     int a[]= {0,20,30};
     System.out.println(a[2]);
     }
     catch(ArrayIndexOutOfBoundsException k)
     {
     System.out.println(k);
     }
     System.out.println(10/0);
     }
     catch(ArithmeticException e)
     {
     System.out.println(e);
     }
     System.out.println("main method end");
      }
}
 

output:

main method started
30
java.lang.ArithmeticException: / by zero
main method end
